# Generated by Django 4.2.1 on 2023-06-06 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_booked_by_room_check_in_room_check_out_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult_count',
            field=models.IntegerField(default=1, verbose_name='Кол-во взрослых'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заезда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выезда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='child_count',
            field=models.IntegerField(blank=True, default=1, verbose_name='Кол-во детей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время бронирования'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
    ]
