# Generated by Django 4.2.1 on 2023-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_delete_temporarybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='category', max_length=50, verbose_name='Slug для фильтра'),
        ),
    ]
