# Generated by Django 4.2.1 on 2023-06-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Стоимость за ночь'),
        ),
    ]
