# Generated by Django 3.2.19 on 2023-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='child_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во детей'),
        ),
    ]
